name: "DAST"
description: "DAST Step"

inputs:
  ENABLED:
    description: "Enable step"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Compose
      if: ${{inputs.ENABLED=='true'}}
      run: docker compose version
      shell: bash

    - name: Run ZAP Scan
      if: ${{inputs.ENABLED=='true'}}
      run: |
        mkdir -p ./zap-output
        chmod -R 777 ./zap-output
        docker compose up --abort-on-container-exit
      shell: bash

