name: "Integration Tests"
description: "Integration Tests Step"

inputs:
  ENABLED:
    description: "Enable step"
    required: false
    default: "true"
  DOCKER_USERNAME:
    description: "DOCKER USERNAME"
    required: true
  DOCKER_PASSWORD:
    description: "DOCKER PASSWORD"
    required: true
#  DOCKER_NAMESPACE:
#    description: "DOCKER NAMESPACE"
#    required: true
#  DOCKER_REGISTRY_IMAGE:
#    description: "DOCKER REGISTRY IMAGE"
#    required: true
  VERSION:
    description: "DOCKER REGISTRY IMAGE"
    required: true
  IMAGE_FULL_NAME:
    description: "At the form: Username/image-name"
    required: true



runs:
  using: "composite"
  steps:
    - name: "Dockerization"
      if: ${{inputs.ENABLED=='true'}}
      run: |
        echo "⚙️ Build docker image with versions :${{inputs.VERSION}},latest "
        docker login -u=${{inputs.DOCKER_USERNAME }} -p=${{ inputs.DOCKER_PASSWORD }}
#        echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USER }}" --password-stdin
        docker build -t ${{inputs.IMAGE_FULL_NAME}}:${{inputs.VERSION}} -t ${{inputs.IMAGE_FULL_NAME}}:latest .        
        docker push ${{inputs.IMAGE_FULL_NAME}}:${{inputs.VERSION}}
        docker push ${{inputs.IMAGE_FULL_NAME}}:latest
      shell: bash