version: '3'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - "80:80"
    volumes:
      - drone-server-data:/data
    restart: always
    environment:
     DRONE_SERVER_HOST: localhost
     DRONE_SERVER_PROTO: http
     DRONE_GITHUB_CLIENT_ID: Ov23liMiENtKqIxz8RjV
     DRONE_GITHUB_CLIENT_SECRET: 8bfa16159a0e5f2e7d96ddd50c82ec02d158f4d1
     DRONE_RPC_SECRET: a3ac66
     DRONE_USER_CREATE: username:seenibu,admin:true
     DRONE_AGENTS_ENABLED: true
  #    env_file:
#      - docker-compose-secret.env

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone-server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone-server
      DRONE_RPC_SECRET: a3ac66
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: drone-runner
#    env_file:
#      - docker-compose-secret.env

volumes:
  drone-server-data:
