version: '2'
services:
  service-postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata: