name: "Integration Tests"
description: "Integration Tests Step"

inputs:
  ENABLED:
    description: "Enable step"
    required: false
    default: "true"
  PROJECT_KEY :
    description: "Sonar project key"
    required: true
  SONAR_TOKEN:
    description: "SONAR TOKEN"
    required: true
  SONAR_HOST:
    description: "Sonar Host"
    required: false
    default: "https://sonarcloud.io"

runs:
  using: "composite"
  steps:
    - name: "Quality gate"
      if: ${{inputs.ENABLED=='true'}}
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      run: |
        echo "🧪 Running quality gate ..."
        mvn -B clean verify sonar:sonar -Dsonar.projectKey=${{inputs.PROJECT_KEY}}
      shell: bash

    - name: "Check Quality Gate"
      if: ${{inputs.ENABLED=='true'}}
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      run: |
        PROJECT_KEY=${{inputs.PROJECT_KEY}}
        ANALYSIS_STATUS_URL="${{ inputs.SONAR_HOST }}/api/qualitygates/project_status?projectKey=${{inputs.PROJECT_KEY}}"

        echo "🔄 Waiting for Quality Gate to be ready ..."
        sleep 5

        STATUS=$(curl -s -u ${{inputs.PROJECT_KEY}}: "$ANALYSIS_STATUS_URL" | jq -r '.projectStatus.status')

        echo "Quality Gate Status : $STATUS"
        if [ "$STATUS" != "OK" ]; then
          echo "❌ Quality Gate failed, status = $STATUS !"
          exit 1
        fi
        echo "🚀🔸🔹👉 Find analysis result at : $ANALYSIS_STATUS_URL"
      shell: bash