name: Build Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
     ENABLE_SECRETS_SCAN: false
     ENABLE_DEPENDENCIES_SCAN: false
     ENABLE_TESTS: true
     ENABLE_SONAR_SCAN: false
     ENABLE_PACKAGE: true
     ENABLE_RELEASE: true
     ENABLE_DOCKERIZATION: true
     ENABLE_DEPLOY: false
     ENABLE_DAST: false

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-env

      - uses: ./.github/actions/secrets-scan
        with:
          ENABLED: ${{ env.ENABLE_SECRETS_SCAN }}

      - uses: ./.github/actions/dependency-scan
        with:
          ENABLED: ${{ env.ENABLE_DEPENDENCIES_SCAN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - uses: ./.github/actions/tests
        with:
          ENABLED: ${{ env.ENABLE_TESTS }}

      - uses: ./.github/actions/quality-gate
        with:
          ENABLED: ${{ env.ENABLE_SONAR_SCAN }}
          PROJECT_KEY: "seenibu_todos"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: "https://sonarcloud.io"

      - uses: ./.github/actions/package
        with:
          ENABLED: ${{ env.ENABLE_PACKAGE }}

      - uses: ./.github/actions/release
        id: release
        with:
          ENABLED: ${{ env.ENABLE_RELEASE }}

      - uses: ./.github/actions/dockerization
        with:
          ENABLED: ${{ env.ENABLE_DOCKERIZATION }}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{steps.release.outputs.VERSION}}
          IMAGE_FULL_NAME: ${{secrets.DOCKER_NAMESPACE}}/${{secrets.DOCKER_REGISTRY_IMAGE}}

      - uses: ./.github/actions/deploy
        with:
          ENABLED: ${{ env.ENABLE_DEPLOY }}

      - uses: ./.github/actions/dast-in-docker
        with:
          ENABLED: ${{ env.ENABLE_DAST }}
