name: Build Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOT_ACTIONS: ./.github/actions

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ${{env.ROOT_ACTIONS}}/setup-env

      - uses: ${{env.ROOT_ACTIONS}}/dependency-scan
        with:
          ENABLED : "false"
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - uses: ${{env.ROOT_ACTIONS}}/tests

      - uses: ${{env.ROOT_ACTIONS}}/quality-gate
        with:
          ENABLED : "false"
          PROJECT_KEY: "seenibu_todos"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: "https://sonarcloud.io"

      - uses: ${{env.ROOT_ACTIONS}}/package

      - uses: ${{env.ROOT_ACTIONS}}/release
        id : release
        with:
          ENABLED : "false"

      - uses: ${{env.ROOT_ACTIONS}}/dockerization
        with:
          ENABLED : "false"
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{steps.release.outputs.VERSION}}
          IMAGE_FULL_NAME:  ${{secrets.DOCKER_NAMESPACE}}/${{secrets.DOCKER_REGISTRY_IMAGE}}

      - uses: ${{env.ROOT_ACTIONS}}/deploy
        with:
          ENABLED : "false"
