name: Pull Request
on:
  pull_request:
#    types: [opened, synchronize, reopened]
     branches:
       - DIC1-*
       - IS-*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROOT_ACTIONS: ./.github/actions

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ${{env.ROOT_ACTIONS}}/setup-env

      - uses: ${{env.ROOT_ACTIONS}}/dependency-scan
        with:
          ENABLED : "false"
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - uses: ${{env.ROOT_ACTIONS}}/tests

      - uses: ${{env.ROOT_ACTIONS}}/quality-gate
        with:
          ENABLED : "false"
          PROJECT_KEY: "seenibu_todos"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: "https://sonarcloud.io"

      - uses: ${{env.ROOT_ACTIONS}}/package

