name: Pull Request
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENABLE_TESTS: false
      ENABLE_DEPENDENCIES_SCAN: false
      ENABLE_SONAR_SCAN: false
      ENABLE_SONAR_CHECK_SCAN: false
      ENABLE_DOCKER_BUILD_AND_PUSH_IMAGE: false
      ENABLE_DEPLOY: false
      ENABLE_WAIT_DEPLOY: false
      ENABLE_CHECK_DEPLOY: false
      ENABLE_PACKAGE: false
      ENABLE_INCREMENT_VERSION: true
      ENABLE_COMMIT_INCREMENT_VERSION: true
      ENABLE_PUSH_TAG: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Dependencies Scan
        if: ${{env.ENABLE_DEPENDENCIES_SCAN=='true'}}
        run: mvn clean verify -DskipTests -Pcve

      - name: Unit Tests
        run: mvn test -Put

      - name: Integration Tests
        run: mvn test -Pit

      - name: "Quality gate"
        if: ${{env.ENABLE_SONAR_SCAN=='true'}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify sonar:sonar -Dsonar.projectKey=seenibu_todos

      - name: "Check Quality Gate"
        if: ${{env.ENABLE_SONAR_CHECK_SCAN=='true'}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PROJECT_KEY=seenibu_todos
          ANALYSIS_STATUS_URL="https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY"
          
          echo "Waiting for Quality Gate result..."
          sleep 5
          
          STATUS=$(curl -s -u $SONAR_TOKEN: "$ANALYSIS_STATUS_URL" | jq -r '.projectStatus.status')
          
          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi