name: Pull Request
on:
  push:
     branches:
       - 'DIC1-*'
       - 'IS-*'


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENABLE_TESTS: true
      ENABLE_SECRETS_SCAN: true
      ENABLE_DEPENDENCIES_SCAN: false
      ENABLE_SONAR_SCAN: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-env

      - uses: ./.github/actions/secrets-scan
        with:
          ENABLED: ${{ env.ENABLE_SECRETS_SCAN }}

      - uses: ./.github/actions/dependency-scan
        with:
          ENABLED: ${{ env.ENABLE_DEPENDENCIES_SCAN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - uses: ./.github/actions/tests
        with:
          ENABLED: ${{ env.ENABLE_TESTS }}

      - uses: ./.github/actions/quality-gate
        with:
          ENABLED: ${{ env.ENABLE_SONAR_SCAN }}
          PROJECT_KEY: "seenibu_todos"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: "https://sonarcloud.io"